name: Run lint & unit tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: "Run unit tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install --prefer-binary -e ".[dev]"

      - name: Run lint
        run: make lint

      - name: Setup environment
        run: make setup

      - name: Run unit tests
        run: make test
